--Diccionario de datos.

SELECT DISTINCT
    a.TABLE_NAME AS NOMBRE_TABLA,
    a.COLUMN_NAME AS NOMBRE_COLUMNA,
    a.DATA_TYPE AS TIPO_DE_DATO,
    PG_CATALOG.COL_DESCRIPTION(b.OID,a.DTD_IDENTIFIER::int) AS DESCRIPCION,
    d.UNIQUE_CONSTRAINT_NAME AS NOMBRE_PK,
    c.CONSTRAINT_NAME AS NOMBRE_FK,
    COALESCE(A.NUMERIC_PRECISION,A.CHARACTER_MAXIMUM_LENGTH) AS LONGITUD_CADENA
FROM INFORMATION_SCHEMA.COLUMNS a
JOIN PG_CLASS b ON a.TABLE_NAME = b.RELNAME
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE c ON c.TABLE_NAME = a.TABLE_NAME
JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS d ON c.CONSTRAINT_NAME = d.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE e ON c.TABLE_NAME = e.TABLE_NAME
WHERE 
    a.TABLE_SCHEMA = 'public'
ORDER BY
    a.TABLE_NAME;

